<a href="https://colab.research.google.com/github/MisterGusMan/IGTI_Bootcamp_ML/blob/main/M%C3%B3dulo%203/Desafio_M%C3%B3dulo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv('ilpd.csv')

In [50]:
df.head()

V1      V2    V3   V4   V5  V6   V7   V8   V9   V10  Class
0  65  Female   0.7  0.1  187  16   18  6.8  3.3  0.90      1
1  62    Male  10.9  5.5  699  64  100  7.5  3.2  0.74      1
2  62    Male   7.3  4.1  490  60   68  7.0  3.3  0.89      1
3  58    Male   1.0  0.4  182  14   20  6.8  3.4  1.00      1
4  72    Male   3.9  2.0  195  27   59  7.3  2.4  0.40      1

In [21]:
df.describe()

V1          V3          V4  ...          V9         V10       Class
count  583.000000  583.000000  583.000000  ...  583.000000  583.000000  583.000000
mean    44.746141    3.298799    1.486106  ...    3.141852    0.947064    1.286449
std     16.189833    6.209522    2.808498  ...    0.795519    0.318492    0.452490
min      4.000000    0.400000    0.100000  ...    0.900000    0.300000    1.000000
25%     33.000000    0.800000    0.200000  ...    2.600000    0.700000    1.000000
50%     45.000000    1.000000    0.300000  ...    3.100000    0.947064    1.000000
75%     58.000000    2.600000    1.300000  ...    3.800000    1.100000    2.000000
max     90.000000   75.000000   19.700000  ...    5.500000    2.800000    2.000000

[8 rows x 10 columns]

# # 1. O objetivo dessa base é avaliar se uma pessoa vai ser um paciente hepático ou não. A feature que determina a classe nessa base é a “V7”. 

Falso, nosso target é a coluna `class`, que define se o paciente é hepático (1) ou não (2) dependendo das suas features (V1-V10).

In [22]:
# 2. Sobre as informações de número de features e amostras, marque a alternativa CORRETA. 
df.shape

(583, 11)

# 3. Essa base conta com 3 atributos categóricos. Precisamos fazer o pré processamento desses atributos para que todos sejam numéricos. 

Falso, temos apenas dois atributos categóricos: V2 e Class. Vamos alterar seus valores para numéricos:

In [62]:
df['Class'].unique()

array([1, 2])

In [63]:
df['V2'].unique()

array(['Female', 'Male'], dtype=object)

In [64]:
df['Class'] = pd.get_dummies(df['Class'])

In [65]:
df['V2'] = pd.get_dummies(df['V2'])

In [66]:
df['V2'].unique()

array([1, 0], dtype=uint8)

In [67]:
df['Class'].unique()

array([1, 0], dtype=uint8)

In [68]:
df.head()

V1  V2    V3   V4   V5  V6   V7   V8   V9   V10  Class
0  65   1   0.7  0.1  187  16   18  6.8  3.3  0.90      1
1  62   0  10.9  5.5  699  64  100  7.5  3.2  0.74      1
2  62   0   7.3  4.1  490  60   68  7.0  3.3  0.89      1
3  58   0   1.0  0.4  182  14   20  6.8  3.4  1.00      1
4  72   0   3.9  2.0  195  27   59  7.3  2.4  0.40      1

In [69]:
# 4. A base não tem dados faltantes. 
df.isnull().values.any()

False

# Pré processamento dos dados:

In [71]:
labels = np.array(df['Class'])

feat_list = list(df.columns)

In [72]:
df = df.drop('Class', axis = 1)

data = np.array(df)

In [73]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,

In [74]:
data

array([[65.  ,  1.  ,  0.7 , ...,  6.8 ,  3.3 ,  0.9 ],
       [62.  ,  0.  , 10.9 , ...,  7.5 ,  3.2 ,  0.74],
       [62.  ,  0.  ,  7.3 , ...,  7.  ,  3.3 ,  0.89],
       ...,
       [52.  ,  0.  ,  0.8 , ...,  6.4 ,  3.2 ,  1.  ],
       [31.  ,  0.  ,  1.3 , ...,  6.8 ,  3.4 ,  1.  ],
       [38.  ,  0.  ,  1.  , ...,  7.3 ,  4.4 ,  1.5 ]])

# Montagem e otimização do modelo SVC:


In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from scipy.stats import uniform, randint
from sklearn.metrics import f1_score, make_scorer

In [95]:
# Definindo o tipo de validação cruzada (Kfold):
cv_strat = StratifiedKFold(n_splits=10)

# Definindo o score da classificação (f1):
f1 = make_scorer(f1_score)

# Definindo hiperparâmetros do SVC:
param_dist_svc = dict(kernel = ['sigmoid', 'poly', 'rbf'], C = uniform(loc = 1, scale = 10))

# Instânciando o classificador SVC:
svc = SVC()

# Instânciando e ajustando o random search com os parâmetros definidos anteriormente:
random_cv_svc = RandomizedSearchCV(svc, param_dist_svc, cv = cv_strat, scoring = f1, random_state = 54, n_iter = 5) 
random_cv_svc.fit(data, labels)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
                   error_score=nan,
                   estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                 class_weight=None, coef0=0.0,
                                 decision_function_shape='ovr', degree=3,
                                 gamma='scale', kernel='rbf', max_iter=-1,
                                 probability=False, random_state=None,
                                 shrinking=True, tol=0.001, verbose=False),
                   iid='deprecated', n_iter=5, n_jobs=None,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f18dd53ead0>,
                                        'kernel': ['sigmoid', 'poly', 'rbf']},
                   pre_dispatch='2*n_jobs', random_state=54, refit=True,
                   return_train_score=False, scoring=make_scorer(f1_score),
                   verbose=0)

In [96]:
# Retornando os melhores resultados do random search para o classificador SVC (questões 5 a 8):
print(f'Melhor f1: {random_cv_svc.best_score_}, \n\nMelhores Parâmetros: {random_cv_svc.best_params_} \n\nMelhor Estimador: {random_cv_svc.best_estimator_} ')

Melhor f1: 0.832818081808181, 

Melhores Parâmetros: {'C': 5.201829671407738, 'kernel': 'rbf'} 

Melhor Estimador: SVC(C=5.201829671407738, break_ties=False, cache_size=200, class_weight=None,
    coef0=0.0, decision_function_shape='ovr', degree=3, gamma='scale',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False) 


# Montagem e otimização do modelo Random Forest:

In [98]:
# Definindo o tipo de validação cruzada (Kfold):
cv_strat = StratifiedKFold(n_splits=10)

# Definindo o score da classificação (f1):
f1 = make_scorer(f1_score)

# Definindo hiperparâmetros do RandomForestClassifier:
param_dist_rfc = dict(bootstrap = [True, False], criterion = ['gini', 'entropy'], n_estimators = randint(10, 1000))

# Instânciando o classificador SVC:
rfc = RandomForestClassifier(random_state= 54)

# Instânciando e ajustando o random search com os parâmetros definidos anteriormente:
random_cv_rfc = RandomizedSearchCV(rfc, param_dist_rfc, cv = cv_strat, scoring = f1, random_state = 54, n_iter = 5) 
random_cv_rfc.fit(data, labels)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
                   error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_s...
                     

In [99]:
# Retornando os melhores resultados do random search para o classificador RandomForestClassifier (questões 9 a 12):
print(f'Melhor f1: {random_cv_rfc.best_score_}, \n\nMelhores Parâmetros: {random_cv_rfc.best_params_} \n\nMelhor Estimador: {random_cv_rfc.best_estimator_} ')

Melhor f1: 0.7953796472310697, 

Melhores Parâmetros: {'bootstrap': True, 'criterion': 'gini', 'n_estimators': 913} 

Melhor Estimador: RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=913,
                       n_jobs=None, oob_score=False, random_state=54, verbose=0,
                       warm_start=False) 
