<a href="https://colab.research.google.com/github/MisterGusMan/IGTI_Bootcamp_ML/blob/main/M%C3%B3dulo%203/TrabalhoPratico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Trabalho Pratico**

---

Métricas de Desempenho

### *Importando* bibliotecas


In [5]:
import pandas as pd #biblioteca para manipulação de dados
import numpy as np #biblioteca para utilizacao de vetores e matrizes
import matplotlib.pyplot as plt #bibloteca para plotar graficos

### Carregamento dos dados

In [6]:
#lendo o csv que contem as base de dados em dfs
df_r = pd.read_csv('diabetes_numeric.csv')
df_cf = pd.read_csv('bloodtransf.csv')
df_cs = pd.read_csv('wine.csv')


In [7]:
#imprimindo as 5 primeiras linhas do df para confirmação
df_r.head(5)


age  deficit  c_peptide
0   5.2     -8.1        4.8
1   8.8    -16.1        4.1
2  10.5     -0.9        5.2
3  10.6     -7.8        5.5
4  10.4    -29.0        5.0

In [8]:
df_cf.head(5)


V1  V2     V3  V4  Class
0   2  50  12500  98      2
1   0  13   3250  28      2
2   1  16   4000  35      2
3   2  20   5000  45      2
4   1  24   6000  77      1

In [9]:
df_cs.head(5)


class  Alcohol  Malic_acid  ...   Hue  OD280%2FOD315_of_diluted_wines  Proline
0      1    14.23        1.71  ...  1.04                            3.92     1065
1      1    13.20        1.78  ...  1.05                            3.40     1050
2      1    13.16        2.36  ...  1.03                            3.17     1185
3      1    14.37        1.95  ...  0.86                            3.45     1480
4      1    13.24        2.59  ...  1.04                            2.93      735

[5 rows x 14 columns]

In [10]:
# Verificando o numero de amostras (linhas) e features (colunas) do dataset. 
print('Amostras e Features:', df_r.shape)
print('Amostras e Features:', df_cf.shape)
print('Amostras e Features:', df_cs.shape)

Amostras e Features: (43, 3)
Amostras e Features: (748, 5)
Amostras e Features: (178, 14)


In [11]:
# Verificando quais são os tipos das features
df_r.columns


Index(['age', 'deficit', 'c_peptide'], dtype='object')

In [12]:
df_cf.columns

Index(['V1', 'V2', 'V3', 'V4', 'Class'], dtype='object')

In [13]:
df_cs.columns

Index(['class', 'Alcohol', 'Malic_acid', 'Ash', 'Alcalinity_of_ash',
       'Magnesium', 'Total_phenols', 'Flavanoids', 'Nonflavanoid_phenols',
       'Proanthocyanins', 'Color_intensity', 'Hue',
       'OD280%2FOD315_of_diluted_wines', 'Proline'],
      dtype='object')

### Pré processamento

In [14]:
print(np.unique(df_cf['Class']))
print(np.unique(df_cs['class']))

[1 2]
[1 2 3]


Mapeamentos das classes

In [15]:
#criando um dicionario de dados para o mapeamento
name_to_class = {
    1: 0,
    2: 1
}

#substituindo os valores categóricos pelo mapeamento
df_cf['Class'] = df_cf['Class'].map(name_to_class)

#check
df_cf.head(5)

V1  V2     V3  V4  Class
0   2  50  12500  98      1
1   0  13   3250  28      1
2   1  16   4000  35      1
3   2  20   5000  45      1
4   1  24   6000  77      0

In [16]:
#criando um dicionario de dados para o mapeamento
name_to_class = {
    1: 0,
    2: 1,
    3: 2

}

#substituindo os valores categóricos pelo mapeamento
df_cs['class'] = df_cs['class'].map(name_to_class)

#check
df_cs.head(5)

class  Alcohol  Malic_acid  ...   Hue  OD280%2FOD315_of_diluted_wines  Proline
0      0    14.23        1.71  ...  1.04                            3.92     1065
1      0    13.20        1.78  ...  1.05                            3.40     1050
2      0    13.16        2.36  ...  1.03                            3.17     1185
3      0    14.37        1.95  ...  0.86                            3.45     1480
4      0    13.24        2.59  ...  1.04                            2.93      735

[5 rows x 14 columns]

Uma outra etapa importante do pré-processamento consiste na avaliação de dados faltantes. 



In [17]:
# Analisando o resumo da base
df_r.describe()


age    deficit  c_peptide
count  43.000000  43.000000  43.000000
mean    9.032558  -8.148837   4.746512
std     4.022539   7.123080   0.720565
min     0.900000 -29.000000   3.000000
25%     5.500000 -12.700000   4.450000
50%    10.400000  -7.800000   4.900000
75%    11.850000  -2.000000   5.100000
max    15.600000  -0.200000   6.600000

In [18]:
df_cf.describe()

V1          V2            V3          V4       Class
count  748.000000  748.000000    748.000000  748.000000  748.000000
mean     9.506684    5.514706   1378.676471   34.282086    0.237968
std      8.095396    5.839307   1459.826781   24.376714    0.426124
min      0.000000    1.000000    250.000000    2.000000    0.000000
25%      2.750000    2.000000    500.000000   16.000000    0.000000
50%      7.000000    4.000000   1000.000000   28.000000    0.000000
75%     14.000000    7.000000   1750.000000   50.000000    0.000000
max     74.000000   50.000000  12500.000000   98.000000    1.000000

In [19]:
df_cs.describe()

class     Alcohol  ...  OD280%2FOD315_of_diluted_wines      Proline
count  178.000000  178.000000  ...                      178.000000   178.000000
mean     0.938202   13.000618  ...                        2.611685   746.893258
std      0.775035    0.811827  ...                        0.709990   314.907474
min      0.000000   11.030000  ...                        1.270000   278.000000
25%      0.000000   12.362500  ...                        1.937500   500.500000
50%      1.000000   13.050000  ...                        2.780000   673.500000
75%      2.000000   13.677500  ...                        3.170000   985.000000
max      2.000000   14.830000  ...                        4.000000  1680.000000

[8 rows x 14 columns]

Os modelos implementados no sklearn recebem como entrada para a modelagam um ou mais arrays. Dessa forma, precisamos modificar o df original para que seja possível a modelagem correta. 

Para isso, vamos separar o label das amotras, armazenar o nome das featues já que os arrays não fazem isso e depois retirar a coluna de labels do df original. Em seguida, vamos converter o df para array usando o numpy!

In [20]:
#df regressor

# armazenando os labels em um array
labels_r = np.array(df_r['c_peptide'])

# salvando a ordem das features
feature_list_r = list(df_r.columns)

# removendo a coluna de labels do df original
df_r = df_r.drop('c_peptide', axis = 1)

# check
df_r.columns

Index(['age', 'deficit'], dtype='object')

In [21]:
# convertendo df para array
data_r = np.array(df_r)

In [22]:
#df classifiers

# armazenando os labels em um array
labels_cf = np.array(df_cf['Class'])

# salvando a ordem das features
feature_list_cf = list(df_cf.columns)

# removendo a coluna de labels do df original
df_cf = df_cf.drop('Class', axis = 1)

# check
df_cf.columns

Index(['V1', 'V2', 'V3', 'V4'], dtype='object')

In [23]:
# convertendo df para array
data_cf = np.array(df_cf)

In [24]:
#df cluster _cs

# armazenando os labels em um array
labels_cs = np.array(df_cs['class'])

# salvando a ordem das features
feature_list_cs = list(df_cs.columns)

# removendo a coluna de labels do df original
df_cs = df_cs.drop('class', axis = 1)

# check
df_cs.columns

Index(['Alcohol', 'Malic_acid', 'Ash', 'Alcalinity_of_ash', 'Magnesium',
       'Total_phenols', 'Flavanoids', 'Nonflavanoid_phenols',
       'Proanthocyanins', 'Color_intensity', 'Hue',
       'OD280%2FOD315_of_diluted_wines', 'Proline'],
      dtype='object')

In [25]:
# convertendo df para array
data_cs = np.array(df_cs)

Agora estamos quase prontos para a modelagem em si!

Precisamos apenas separar uma parte dos nossos dados para que seja possível avaliar os modelos que vamos treinar. O sklearn tem uma função para isso: <a href = http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html> train_test_split<a>.

In [26]:
# importar train_test_split do scikitlearn 
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e 
# teste segundo uma porcentagem de separação definida. 

#regressao
train_reg, test_reg, train_labels_reg, test_labels_reg = train_test_split(data_r, labels_r, test_size = 0.35, random_state = 54)

#classificação
train_class, test_class, train_labels_class, test_labels_class = train_test_split(data_cf, labels_cf, test_size = 0.35, random_state = 54)

#clustering
train_clust, test_clust, train_labels_clust, test_labels_clust = train_test_split(data_cs, labels_cs, test_size = 0.35, random_state = 54)


### Regressão Linear

In [27]:
# importar o modelo de regressão linear
from sklearn.linear_model import LinearRegression 

# treinando o modelo no conjunto de dados de treino
regression = LinearRegression().fit(train_reg, train_labels_reg);

In [28]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions1_labels = regression.predict(test_reg)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels_reg, 'Previsto': predictions1_labels})  
p.head(10)

Real  Previsto
0   4.8  5.149704
1   5.1  4.535149
2   5.3  5.119985
3   3.7  4.904753
4   5.1  5.233693
5   3.9  4.634138
6   6.0  5.364907
7   5.1  4.663731
8   3.9  4.499411
9   4.9  5.495559

Agora que criamos o modelo de regressão linear e aplicamos o modelo criado ao conjunto de teste, podemos então avaliar o modelo gerado. 

In [29]:
from sklearn import metrics
#avaliando o modelo
print('R2:', metrics.r2_score(test_labels_reg, predictions1_labels)) 
print('MSE:', metrics.mean_squared_error(test_labels_reg, predictions1_labels))  
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels_reg, predictions1_labels))) 
print('RMSLE:', np.sqrt(metrics.mean_squared_log_error(test_labels_reg, predictions1_labels))) 
print('MAE:', metrics.mean_absolute_error(test_labels_reg, predictions1_labels))

R2: 0.2730761502482787
MSE: 0.40159703152494497
RMSE: 0.6337168385998158
RMSLE: 0.11831951316295629
MAE: 0.5469803958260979


### Classificação com SVM

In [30]:
#importar o modelo SVR
from sklearn.svm import SVC

# instanciacao e determinacao dos hiperparâmetros do SVR: tipo de kernel e epsilon
classifier = SVC(kernel='rbf')

# treinando o SVR
classifier.fit(train_class,train_labels_class)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [31]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions2_labels = classifier.predict(test_class)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels_class, 'Previsto': predictions2_labels})  
p.head(10)

Real  Previsto
0     0         0
1     1         0
2     1         0
3     0         0
4     0         0
5     1         0
6     0         0
7     0         0
8     0         0
9     0         0

In [32]:
print('\nAcurácia\n', metrics.accuracy_score(test_labels_class, predictions2_labels)) 
print('\nAcurácia Balanceada por classe\n', metrics.balanced_accuracy_score(test_labels_class, predictions2_labels)) 
print('\nPrecision\n', metrics.precision_score(test_labels_class, predictions2_labels)) 
print('\nRecall\n', metrics.recall_score(test_labels_class, predictions2_labels)) 
print('\nF1\n', metrics.f1_score(test_labels_class, predictions2_labels)) 

print('\nAUCROC\n', metrics.roc_auc_score(test_labels_class, predictions2_labels))


Acurácia
 0.7595419847328244

Acurácia Balanceada por classe
 0.5

Precision
 0.0

Recall
 0.0

F1
 0.0

AUCROC
 0.5


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
print(metrics.classification_report(test_labels_class, predictions2_labels))

              precision    recall  f1-score   support

           0       0.76      1.00      0.86       199
           1       0.00      0.00      0.00        63

    accuracy                           0.76       262
   macro avg       0.38      0.50      0.43       262
weighted avg       0.58      0.76      0.66       262



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Clustering com Kmeans

In [34]:
# importar o modelo de KMeans
from sklearn.cluster import KMeans

clustering = KMeans(n_clusters = 3, random_state = 54)
 
# treinando o modelo no conjunto de dados de treino
clustering.fit(train_clust);

In [35]:
predictions3_labels = clustering.predict(test_clust)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels_clust, 'Previsto': predictions3_labels})  
p.head(10)

Real  Previsto
0     0         1
1     0         2
2     1         0
3     2         0
4     1         0
5     0         1
6     1         1
7     1         0
8     2         2
9     2         2

In [36]:
from sklearn.metrics import cluster

#avaliando o modelo
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_clust, predictions3_labels)) 
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_clust, predictions3_labels)) 

print('\nMatriz de Contingência\n', metrics.cluster.contingency_matrix(test_labels_clust, predictions3_labels)) 
print('\nMutual informtion\n', metrics.mutual_info_score(test_labels_clust, predictions3_labels)) 

Coeficiente de Silhueta
 0.5581747258825842

Davies-Bouldin Score
 0.5316199338449925

Matriz de Contingência
 [[ 0 13  6]
 [17  1  5]
 [ 6  0 15]]

Mutual informtion
 0.42739927199674965
